name: flutter_proyecto_recordatorios
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5'

dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.2.0
  flutter_timezone: ^1.0.7
  rxdart: ^0.27.7
  timezone: ^0.9.2
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true